/*Right upper teeth from 1 to 8*/
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('CANINE');
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('INCISOR');

/*Left upper teeth from 9 to 16*/
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('CANINE');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');

/*Left low teeth from 17 to 24*/
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('CANINE');
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('INCISOR');

/*Right low teeth from 25 to 32*/
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('INCISOR');
insert into teeth ( type) values ('CANINE');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('PREMOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');
insert into teeth ( type) values ('MOLAR');